# Generated by Django 3.2.18 on 2023-03-31 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='detalle_principal',
            field=models.TextField(blank=True, null=True),
        ),
    ]
