# Generated by Django 3.2.18 on 2023-03-31 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_blog_detalle_principal'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen_2',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
