# Generated by Django 3.2.18 on 2023-08-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proyecto',
            name='rol_realizado',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
