# Generated by Django 3.2.18 on 2023-08-06 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_proyecto_empresa'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='tipo_proyecto',
            field=models.CharField(blank=True, choices=[('S', 'Software'), ('D', 'Diseño'), ('F', 'Fotografía')], max_length=50, null=True),
        ),
    ]
