# Generated by Django 3.2.18 on 2023-08-11 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_respuestablog_fecha_hora'),
    ]

    operations = [
        migrations.AlterField(
            model_name='respuestablog',
            name='blog',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.blog'),
        ),
    ]
