# Generated by Django 3.2.18 on 2023-08-16 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_quiensoy_img_perfil'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='imagen_portada',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
