# Generated by Django 3.2.18 on 2024-06-24 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_blog_imagen_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.URLField(blank=True, null=True),
        ),
    ]
